# For global module specific settings.

[github]
token = "" #github token

[modules.serverstatus]
default = "default"

[serverstatus]
default = "default"
servername = "default"
type = "ss13"

[nudge]
password = "secret"#nudge password
